### ISSUE TITLE
Avoid passing field count while creating Eventheader struct's, and allow adding fields dynamically

### ISSUE THREAD

**Issue by lalitb** [microsoft/LinuxTracepoints-Rust#5]
In the otel-rust's user_events exporter, the current method involves determining the count of all fields within a struct, setting that count, and then proceeding to add fields. However, would it be feasible to design a system where structs can be created without knowing the count beforehand? By doing so, we could simply pass a reference to the struct while adding a field, ensuring proper mapping (or any better way). This approach would eliminate the need to temporarily cache some fields. Furthermore, we are considering making some changes to our otel-sdk design, particularly when it is impractical to ascertain the count during the serialization process.

**Comment by idigdoug** [comment]
It is feasible to add support for updating the number of fields in a struct. In other words, it is possible to allow you to add a struct(1), then add 24 fields to the struct, and then go back and change the 1 to a 24.

Note that we do not allow struct with 0 fields.

It is NOT feasible to allow you to add fields out of order. Adding that would make the builder much less efficient for everybody, whether or not they take advantage of the functionality. If you don't know the order of your fields, you'll need to cache the fields yourself where needed. That is much more efficient than making every builder always cache everything, which would be inefficient.
